"""column type change

Revision ID: e2af8585d9d5
Revises: 6528d6826d92
Create Date: 2025-07-13 18:09:17.565449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2af8585d9d5'
down_revision: Union[str, None] = '6528d6826d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('assignments', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
