"""added file path

Revision ID: ec033ff1c8ad
Revises: 71ef200e5d21
Create Date: 2025-07-13 21:17:24.558609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec033ff1c8ad'
down_revision: Union[str, None] = '71ef200e5d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('file_path', sa.String(length=255), nullable=False))
    op.drop_column('assignments', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column('assignments', 'file_path')
    # ### end Alembic commands ###
